"""Real-form DEV admission tests use generated bytes and in-memory mock HTTP only."""
from __future__ import annotations

from dataclasses import replace
from hashlib import sha256

import pytest
from test_research_data_binance_archive import zipped
from test_research_data_binance_research_transport import (
    CONSTRAINTS,
    mock_rights,
    response,
)
from test_research_data_contracts import H
from test_research_replay_dev_access import authority, prereg

from trader_assist_v0.contracts.common import sha256_hex
from trader_assist_v0.research_data.admission import AdmissionPolicy
from trader_assist_v0.research_data.binance_archive import (
    DAY_NS,
    ChecksumReceipt,
    checksum_receipt,
    frozen_archive_objects,
)
from trader_assist_v0.research_data.binance_research_transport import (
    MockOnlyResearchTransport,
    PinnedHttpsResearchTransport,
)
from trader_assist_v0.research_data.contracts import ProviderCapability, SourceMode
from trader_assist_v0.research_data.mapping import (
    PitReferenceResolver,
    ReferenceMappingInterval,
    ReferenceMappingSnapshot,
)
from trader_assist_v0.research_inventory.builder import _binding, build_inventory_manifest
from trader_assist_v0.research_inventory.contracts import (
    AllocationItem,
    InventoryAllocationSpec,
    InventoryRole,
    InventoryState,
)
from trader_assist_v0.research_replay.binance_real_dev import (
    FrozenRealDevCandidate,
    _require_historical_bar_only,
    bind_candidate_real_dataset,
    prepare_mock_real_dev_sidecar,
    prepare_real_dev_sidecar,
    require_complete_frozen_receipts,
)
from trader_assist_v0.research_replay.dev_archive import G0_QUESTION, G0_STRATEGY
from trader_assist_v0.research_replay.dev_evidence import (
    DevExternalAdmission,
    read_external_dev,
)
from trader_assist_v0.research_replay.dev_lifecycle import DevVisibilityPolicy

RETRIEVED = 1790000000000000000
R0_REF = "https://github.com/woshixiong/trader-assist-v0/issues/161#issuecomment-6017065560"
R1_REF = "https://github.com/woshixiong/trader-assist-v0/issues/161#issuecomment-6017243748"
RUN_REF = "https://github.com/woshixiong/trader-assist-v0/issues/161#issuecomment-6032019360"


def visibility():
    return DevVisibilityPolicy.create(
        version="G0_REAL_DEV_MOCK_VIS_V1", channel="DEV_LOCAL_AND_AGGREGATE",
        max_rows=288, max_bytes=4_000_000, max_buckets=64,
        aggregate_allowed=True, attribution=("FAKE_TEST_ONLY",),
    )


def mapping():
    records = []
    objects = frozen_archive_objects()
    for symbol in sorted({obj.symbol for obj in objects}):
        first = next(obj for obj in objects if obj.symbol == symbol)
        locator = (
            f"https://data.binance.vision/data/futures/um/daily/klines/{symbol}/5m/"
        )
        records.append(ReferenceMappingInterval.create(
            version="G0_REAL_DEV_MOCK_HIST_MAPPING_V1",
            provider="BINANCE", venue="BINANCE_UM", source_role="RESEARCH_IMPORT",
            native_symbol=symbol, instrument_id=symbol, product="USD_M_FUTURES",
            contract_specification=tuple(
                (key, f"UNVERIFIED_OUTSIDE_BAR_SCOPE:{key}")
                for key in (
                    "multiplier", "settlement", "expiry", "convention",
                    "price_tick", "size_step",
                )
            ),
            price_unit="USD", size_unit="CONTRACTS", currency="USDT",
            reference_currency="USDT", listing_state="LISTED",
            valid_from=first.start_ns,
            valid_to=max(obj.end_ns for obj in objects
                         if obj.symbol == symbol and obj.role_intent == "CURRENT_DEV"),
            known_at=RETRIEVED, recorded_at=RETRIEVED,
            metadata_hash=H, source_locator=locator,
            source_locator_hash=sha256_hex(locator.encode()),
            association=symbol, metadata_basis="HISTORICAL",
            support_state="AVAILABLE_VERIFIED",
        ))
    return ReferenceMappingSnapshot.create(
        version="G0_REAL_DEV_MOCK_HIST_MAPPING_SNAPSHOT_V1", records=tuple(records)
    )


def fake_receipts(first_payload: bytes) -> tuple[ChecksumReceipt, ...]:
    result = []
    objects = frozen_archive_objects()
    for index, obj in enumerate(objects):
        archive_hash = sha256(
            first_payload if index == 0 else ("FAKE:" + obj.zip_url).encode()
        ).hexdigest()
        raw = (archive_hash + "  " + obj.zip_name + "\n").encode()
        result.append(checksum_receipt(
            obj, raw, retrieved_at_ns=RETRIEVED,
            retrieval_identity="synthetic://fake-provider-checksum-fixture",
        ))
    return tuple(result)


def inventory(datasets, satisfied):
    objects = frozen_archive_objects()
    by_url = {d.source_locator: d for d in datasets}
    items = []
    for obj in objects:
        ds = by_url[obj.zip_url]
        if obj.role_intent == "CURRENT_DEV":
            role, state, limitations = (
                InventoryRole.CURRENT_DEV, InventoryState.AVAILABLE, (),
            )
        elif obj.role_intent == "FUTURE_DEV_RESERVE":
            role, state, limitations = (
                InventoryRole.FUTURE_DEV_RESERVE, InventoryState.UNKNOWN,
                ("SEALED_FAKE_CHECKSUM_IDENTITY_ONLY",),
            )
        else:
            role, state, limitations = (
                InventoryRole.CERTIFICATION_RESERVE, InventoryState.UNKNOWN,
                ("SEALED_FAKE_CHECKSUM_IDENTITY_ONLY",),
            )
        items.append(AllocationItem(
            binding=_binding(ds), role=role,
            block_id=f"G0_{obj.role_intent}_{obj.symbol}",
            intended_use="STRATEGY_DEV_RESEARCH",
            satisfied_constraints=tuple(sorted(satisfied)),
            inventory_state=state, limitations=limitations,
            reason="FAKE_TEST_ONLY: exercise frozen real-form allocation contract",
        ))
    spec = InventoryAllocationSpec.create(
        spec_id="G0_R3_REAL_DEV_FAKE_ROSTER_V1",
        freeze_evidence_locator=RUN_REF, freeze_evidence_hash=H,
        strategy_version=G0_STRATEGY, primary_research_question=G0_QUESTION,
        items=tuple(items),
    )
    return build_inventory_manifest(datasets=datasets, allocation=spec)


def fixture():
    objects = frozen_archive_objects()
    payload = zipped(objects[0])
    rights = mock_rights()
    snap = mapping()
    proofs = fake_receipts(payload)
    datasets = tuple(
        bind_candidate_real_dataset(
            obj, proof, mapping_hash=snap.record_hash, rights=rights,
            satisfied=CONSTRAINTS,
        )
        for obj, proof in zip(objects, proofs, strict=True)
    )
    vis = visibility()
    dev_hashes = tuple(
        ds.record_hash for obj, ds in zip(objects, datasets, strict=True)
        if obj.role_intent == "CURRENT_DEV"
    )
    reserve_hashes = tuple(
        ds.record_hash for obj, ds in zip(objects, datasets, strict=True)
        if obj.role_intent != "CURRENT_DEV"
    )
    pre = prereg(
        datasets[0], vis=vis, strategy_version=G0_STRATEGY, question=G0_QUESTION,
        r0_ref=R0_REF, r1_ref=R1_REF, run_authority_ref=RUN_REF,
        evidence_kind="RIGHTS_AUTHORIZED_DEV", dataset_hashes=dev_hashes,
        reserve_hashes=reserve_hashes,
    )
    auth = authority(
        datasets[0], pre, satisfied_constraints=tuple(sorted(CONSTRAINTS)),
    )
    cap = ProviderCapability.create(
        version="G0_REAL_DEV_MOCK_CAP_V1",
        provider="BINANCE", venue="BINANCE_UM", product="USD_M_FUTURES",
        source_mode=SourceMode.FREE_REFERENCE_IMPORT, datatype="BAR_5M",
        source_exposes=True,
        source_evidence=(
            "https://github.com/binance/binance-public-data/"
            "blob/master/README.md"
        ),
        adapter_state="AVAILABLE_VERIFIED", adapter_owner="FREE_FILE",
        proof_locator=objects[0].checksum_url, enabled=True,
    )
    policy = AdmissionPolicy.create(
        version="G0_REAL_DEV_MOCK_ADMISSION_V1",
        stale_after_ns=DAY_NS, sequence_semantics="UNKNOWN", max_observations=288,
    )
    admission = DevExternalAdmission(
        datasets[0], PitReferenceResolver(snap), (cap,), policy, auth, pre,
    )
    candidate = FrozenRealDevCandidate(
        proofs, datasets, inventory(datasets, CONSTRAINTS), pre, vis, CONSTRAINTS,
    )
    mock = MockOnlyResearchTransport((response(objects[0].zip_url, payload),))
    return objects, payload, rights, proofs, datasets, candidate, admission, mock


def test_complete_256_roster_is_required_without_hash_fabrication():
    _, _, _, proofs, _, _, _, _ = fixture()
    assert len(require_complete_frozen_receipts(proofs)) == 256
    with pytest.raises(Exception, match="missing 1 exact checksum"):
        require_complete_frozen_receipts(proofs[:-1])
    with pytest.raises(ValueError, match="duplicate"):
        require_complete_frozen_receipts((*proofs[:-1], proofs[0]))


def test_mock_real_form_full_gate_and_existing_reader_roundtrip(tmp_path):
    objects, _, rights, proofs, _, candidate, admission, mock = fixture()
    candidate.require_frozen(rights)
    prepared = prepare_mock_real_dev_sidecar(
        objects[0], proofs[0], admission, candidate,
        mock=mock, output_root=tmp_path, registry_hash=H,
    )
    assert prepared.observations == 288
    assert prepared.encoded_bytes < 4_000_000
    assert prepared.path.exists()
    replay = read_external_dev(
        tmp_path, prepared.path, prepared.checksum, H, admission,
    )
    assert len(replay) == 288
    assert all(row.ts_receive is None for row in replay)
    assert all(row.receive_provenance == "NOT_EXPOSED" for row in replay)
    assert all(row.known_at == RETRIEVED for row in replay)
    with pytest.raises(FileExistsError):
        prepare_mock_real_dev_sidecar(
            objects[0], proofs[0], admission, candidate,
            mock=mock, output_root=tmp_path, registry_hash=H,
        )


def test_partial_or_revised_roster_fails_before_mock_zip_or_write(tmp_path):
    objects, _, rights, proofs, _, candidate, admission, mock = fixture()
    partial = replace(candidate, receipts=proofs[:-1])
    with pytest.raises(Exception, match="missing 1 exact checksum"):
        prepare_mock_real_dev_sidecar(
            objects[0], proofs[0], admission, partial,
            mock=mock, output_root=tmp_path, registry_hash=H,
        )
    changed = replace(proofs[1], archive_sha256="b" * 64)
    revised = replace(candidate, receipts=(proofs[0], changed, *proofs[2:]))
    with pytest.raises(PermissionError, match="immutable binding"):
        revised.require_frozen(rights)
    assert not list(tmp_path.iterdir())


def test_reserve_zip_never_reaches_mock_transport_or_output(tmp_path):
    objects, _, _, proofs, _, candidate, admission, _ = fixture()
    reserve_index = next(
        i for i, obj in enumerate(objects) if obj.role_intent == "FUTURE_DEV_RESERVE"
    )
    reserve = objects[reserve_index]
    trap = MockOnlyResearchTransport((
        response(reserve.zip_url, b"FAKE-RESERVE-BYTES-NEVER-READ"),
    ))
    with pytest.raises(PermissionError, match="reserve"):
        prepare_mock_real_dev_sidecar(
            reserve, proofs[reserve_index], admission, candidate,
            mock=trap, output_root=tmp_path, registry_hash=H,
        )
    assert not list(tmp_path.iterdir())


def test_real_transport_is_still_denied_after_all_mock_readiness(tmp_path, monkeypatch):
    objects, _, _, proofs, _, candidate, admission, _ = fixture()

    def no_resolve(self):
        pytest.fail("filesystem touched after provider gate should have denied")

    monkeypatch.setattr("pathlib.Path.resolve", no_resolve)
    with pytest.raises(PermissionError, match="REAL_PROVIDER_IO_NOT_AUTHORIZED"):
        prepare_real_dev_sidecar(
            objects[0], proofs[0], admission, candidate,
            transport=PinnedHttpsResearchTransport(),
            output_root=tmp_path, registry_hash=H,
        )


def test_backdated_or_synthetic_mapping_is_not_historical_proof():
    objects, _, _, proofs, datasets, _, _, _ = fixture()
    obj, _, proof = objects[0], datasets[0], proofs[0]
    good = mapping().records[0]
    bad_record = ReferenceMappingInterval.create(**{
        **good.model_dump(exclude={"record_hash", "known_at", "recorded_at"}),
        "known_at": obj.start_ns, "recorded_at": obj.start_ns,
    })
    bad_snap = ReferenceMappingSnapshot.create(
        version="BAD_BACKDATED_MOCK", records=(bad_record,),
    )
    bad_ds = bind_candidate_real_dataset(
        obj, proof, mapping_hash=bad_snap.record_hash, rights=mock_rights(),
        satisfied=CONSTRAINTS,
    )
    vis = visibility()
    pre = prereg(
        bad_ds, vis=vis, strategy_version=G0_STRATEGY, question=G0_QUESTION,
        r0_ref=R0_REF, r1_ref=R1_REF, run_authority_ref=RUN_REF,
        evidence_kind="RIGHTS_AUTHORIZED_DEV", dataset_hashes=(bad_ds.record_hash,),
    )
    auth = authority(
        bad_ds, pre, satisfied_constraints=tuple(sorted(CONSTRAINTS)),
    )
    cap = ProviderCapability.create(
        version="BAD_MAPPING_MOCK_CAP", provider="BINANCE", venue="BINANCE_UM",
        product="USD_M_FUTURES", source_mode=SourceMode.FREE_REFERENCE_IMPORT,
        datatype="BAR_5M", source_exposes=True,
        source_evidence="https://data.binance.vision/fake-proof",
        adapter_state="AVAILABLE_VERIFIED", adapter_owner="FREE_FILE",
        proof_locator=obj.checksum_url, enabled=True,
    )
    admission = DevExternalAdmission(
        bad_ds, PitReferenceResolver(bad_snap), (cap,),
        AdmissionPolicy.create(
            version="BAD_MAPPING_POLICY", stale_after_ns=DAY_NS,
            sequence_semantics="UNKNOWN", max_observations=288,
        ),
        auth, pre,
    )
    with pytest.raises(Exception, match="historical mapping"):
        _require_historical_bar_only(obj, proof, admission)
