"""Ordinary VNext G4 development-only strategy/evidence surface."""

from .contracts import (
    G4_EXECUTION_MODEL_VERSION,
    G4_SCHEMA_VERSION,
    NAUTILUS_VERSION,
    REPRESENTATIVE_MARKET_FLOOR,
    VNEXT_DATA_VERSION,
    VNEXT_DERIVATION_VERSION,
    VNEXT_PARAMETER_VERSION,
    VNEXT_POLICY_VERSION,
    VNEXT_STRATEGY_VERSION,
    AttemptStop,
    CandidateConfig,
    CandidateManifest,
    DerivedReplayCacheIdentity,
    Ea3Base,
    EntryActivation,
    EvidenceArtifactHash,
    ExecutionModelConfig,
    ExitPolicy,
    G4RunManifest,
    OrderPrimitive,
    ParticipationDecision,
    ReentryPolicy,
    WinnerAdd,
    WinnerConfirmation,
)
from .evaluator import (
    DecisionResult,
    EvaluationInputs,
    evaluate_participation,
    exit_triggered,
    reentry_allowed,
    winner_confirmed,
)
from .reporting import G4DevelopmentReport, ThesisOutcome, build_development_report

__all__ = [
    "G4_EXECUTION_MODEL_VERSION",
    "G4_SCHEMA_VERSION",
    "NAUTILUS_VERSION",
    "REPRESENTATIVE_MARKET_FLOOR",
    "VNEXT_DATA_VERSION",
    "VNEXT_DERIVATION_VERSION",
    "VNEXT_PARAMETER_VERSION",
    "VNEXT_POLICY_VERSION",
    "VNEXT_STRATEGY_VERSION",
    "AttemptStop",
    "CandidateConfig",
    "CandidateManifest",
    "DecisionResult",
    "DerivedReplayCacheIdentity",
    "Ea3Base",
    "EntryActivation",
    "EvaluationInputs",
    "EvidenceArtifactHash",
    "ExecutionModelConfig",
    "ExitPolicy",
    "G4DevelopmentReport",
    "G4RunManifest",
    "OrderPrimitive",
    "ParticipationDecision",
    "ReentryPolicy",
    "ThesisOutcome",
    "WinnerAdd",
    "WinnerConfirmation",
    "build_development_report",
    "evaluate_participation",
    "exit_triggered",
    "reentry_allowed",
    "winner_confirmed",
]
