"""Deterministic, research-only correlated-signal clustering."""

from .engine import (
    CORRELATION_EVENT_WINDOW,
    CORRELATION_LOOKBACK,
    MIN_PAIRED_RETURNS,
    PRIMARY_THRESHOLD,
    SENSITIVITY_THRESHOLDS,
    CloseObservation,
    Cluster,
    ClusterKind,
    ClusterNormalizedReport,
    CorrelationEngineError,
    CorrelationReport,
    CorrelationStatus,
    LeaderOnlyReport,
    PairwiseCorrelation,
    RawMarketLevelReport,
    SensitivityReport,
    ShadowSignal,
    build_correlation_report,
    pearson_correlation,
)

__all__ = [
    "CORRELATION_EVENT_WINDOW",
    "CORRELATION_LOOKBACK",
    "MIN_PAIRED_RETURNS",
    "PRIMARY_THRESHOLD",
    "SENSITIVITY_THRESHOLDS",
    "CloseObservation",
    "Cluster",
    "ClusterKind",
    "ClusterNormalizedReport",
    "CorrelationEngineError",
    "CorrelationReport",
    "CorrelationStatus",
    "LeaderOnlyReport",
    "PairwiseCorrelation",
    "RawMarketLevelReport",
    "SensitivityReport",
    "ShadowSignal",
    "build_correlation_report",
    "pearson_correlation",
]
